### ISSUE TITLE
Add AppVeyor integration

### ISSUE THREAD

**Issue by cwe1ss** [opentracing-contrib/csharp-grpc#1]
I will add a .appveyor.yml file and I’ll enable the project in our new OpenTracing AppVeyor account.

**Comment by cwe1ss** [comment]
We currently do deployments to NuGet semi-automatically via AppVeyor on the other projects. This ensures that we have a way to do some last checks before the package is live on nuget. 

@Falco20019 Could you please log in to AppVeyor once via your GitHub account (if you don't yet have an AppVeyor account) and send me your email address to christian@chwe.at (or post it here if you want) - I'll then give you permissions to do deployments for this project.

**Comment by cwe1ss** [comment]
@Falco20019 I received your email and I added you as a collaborator to the OpenTracing account. When you log in to AppVeyor it should now prompt you to choose the account/organization you'd like to work with - you have to choose "opentracing" there. 

If I have set up the permissions correctly, you should now be able to do deployments. I didn't want to fiddle around with the AppVeyor permissions too much so you currently have permission to deploy any project - but (obviously) please only deploy your project(s).

The release process currently is:
* Add & push a tag to the git repository (e.g. "0.0.1") - the name must be a valid semantic version!
* AppVeyor should now automatically start the build. This will result in a nuget artifact named "OpenTracing.Contrib.Grpc.0.0.1.nupkg".
* (Do some final tests with this package if you want)
* On the build details, click on "Deploy" (top right) and choose "NuGet (OpenTracing)". This will publish the package to nuget.org (using the "OpenTracing" nuget account)
* Update the release notes on the GitHub release

Let me know if you have any issues or ideas for improvements!

**Comment by cwe1ss** [comment]
Hmm.. sorry, let's keep this open until you've done a release so that we know that everything works.

**Comment by Falco20019** [comment]
Thanks, login already works. I will wait for #7 to be reviewed and merged, and create a pre-release to test deployment. I will also use that pre-release then to test if everything works once https://github.com/jaegertracing/jaeger-client-csharp/issues/62 is released before doing a full release.

**Comment by Falco20019** [comment]
It worked according to AppVeyor (build + deployment). Can you add my account to [OpenTracing.Contrib.Grpc](https://www.nuget.org/packages/OpenTracing.Contrib.Grpc/) as package owner? So that I can fix stuff in the description like the missing `v` in the release link?

**Comment by cwe1ss** [comment]
Unfortunately, package metadata can not be changed after a release: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#managing-packages-on-nugetorg

**Comment by Falco20019** [comment]
Ok, then I think there should be no reason that my NuGet account is owner. I assumed that it may be possible, since the code base for NuGet Gallery (on which I worked recently to add LDAP support) is just extracting and caching the information from the `nupkg` file into the SQL Server database (`dbo.Packages`). But from a design principle it's better to keep metadata immutable, especially for signed packages.
