### ISSUE TITLE
csharp-wcf

### ISSUE THREAD

**Issue by iEmiya** [opentracing-contrib/csharp-grpc#12]
I would like to add a project for integration WCF.
At the moment, the solution is being tested and has proven itself well for tracing soap messages.
[Research.OpenTracing.Wcf](https://github.com/iEmiya/Research.OpenTracing.Wcf)

**Comment by Falco20019** [comment]
Hi, the namespace should match the other packages and should be `OpenTracing.Contrib.Wcf`. The README should be in English so that more people are able to use it.

/CC @yurishkuro

**Comment by iEmiya** [comment]
Done
* rename solution
* translate readme.md

[OpenTracing.Contrib.Wcf](https://github.com/Medialogia/OpenTracing.Contrib.Wcf)
