### ISSUE TITLE
Fix RequestAttribute.Authority and RequestAttribute.AllCallOptions serialization

### ISSUE THREAD

**Issue by Falco20019** [opentracing-contrib/csharp-grpc#3]
The tags for `RequestAttribute.Authority` and `RequestAttribute.AllCallOptions` are serialized using `ToString()`. These classes don't have a good implementation and won't stringify the content but just the class name.

**Comment by MirzaMerdovic** [comment]
Hi,
Is it ok if I take this one?

**Comment by Falco20019** [comment]
Hi @MirzaMerdovic, feel free to fork it and create a pull request once done! I will try to give feedback when needed :)

Thanks for the help!
